# Generated by Django 4.0.3 on 2022-03-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EU', 'Euro'), ('DO', 'Dollars'), ('UA', 'UAH')], default='UA', max_length=2),
        ),
    ]
