# Generated by Django 4.0.3 on 2022-03-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollars'), ('UAH', 'UAH')], default='UAH', max_length=3),
        ),
    ]
